### PR TITLE
Update readme in preparation for archiving

### PR DESCRIPTION
**Pull request by carlosjoan91**

### CODE REVIEW

**Comment by carlosjoan91** [comment]
@devonobrien and @roger2hk: Please take a look, thanks!

**Review by roger2hk — APPROVED** [review]

**Comment by roger2hk** [comment]
It looks like we have to remove `continuous-integration/travis-ci` before merging this PR.

**Comment by roger2hk** [comment]
@carlosjoan91 Please disable the `continuous-integration/travis-ci` by removing the `/.travis.yml`.

@devonobrien PTAL, thanks.

**Comment by roger2hk** [comment]
I have removed the travis mandatory check in the repo branch setting. We should be good to go.

**Pull request merged**
